apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspection-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inspection-api
  template:
    metadata:
      labels:
        app: inspection-api
    spec:
      containers:
      - name: inspection-api
        image: hiteshpant/inspectorapi
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 81
        env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Kubernetes-inspectorapi"
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-inspection-appsettings
---

apiVersion: v1
kind: Service
metadata:
  name: inspection-api
spec:
  selector:
    app: inspection-api
  ports:
  - port: 81
  type: LoadBalancer