apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8-management-alpine
        ports:
          - containerPort: 15672
            protocol: TCP
            name: http
          - containerPort: 5672
            protocol: TCP
            name: amqp

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 15672
    targetPort: 15672
    name: http
    protocol: TCP
  - port: 5672
    targetPort: 5672
    name: amqp
    protocol: TCP
  type: LoadBalancer
