version: '3.4'

services:

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

    volumes:
      - Inspector-sqldata:/var/opt/mssql
      
  reader.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=80
      - PATH_BASE=/reader-api
    ports:
      - "8080:80"
      - "9101:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  inspector.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PATH_BASE=/inspector-api
    ports:
      - "8081:80"
      - "9102:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
volumes:
  Inspector-sqldata:
    external: false
  

   

    
